name: Build KASM Workspace

on:
  push:
    branches:
      - '1.0'
    paths:
      - images/dockerfile-*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            img_name=${changed_file#dockerfile-}
            echo "***** Building ${changed_file}"
            docker build -t ghcr.io/hickey/${img_name}:latest -f ${changed_file} .
            docker push ghcr.io/hickey/${img_name}:latest
          done
        if: steps.changes.outputs.src == 'true'
        with:
          push: true
          file:
          tags: ghcr.io/hickey/:latest