name: Rebuild registry

on:
  push:
    branches-ignore:
      - 'gh-pages'
permissions:
  contents: write
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Changed file: ${changed_file}"
            if [[ "${changed_file}" != "${changed_file%/Dockerfile}" ]]; then
              build_dir=${changed_file%/Dockerfile}
              img_name=$(echo ${build_dir#workspaces/} | tr 'A-Z' 'a-z')

              echo "***** Building ${changed_file}"
              docker build -t ghcr.io/hickey/${img_name}:latest -f ${changed_file} ${build_dir}
              docker push ghcr.io/hickey/${img_name}:latest
            fi
          done
        #if: steps.changes.outputs.src == 'true'

  build:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v3

      - name: Build # Have to run processing first so the list.json exists to be included in the the deploy
        run: |
          npm ci --prefix processing
          npm ci --prefix site
          ./build_all_branches.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
